cargo-features = ["profile-rustflags"]

[package]
name = "libwfa2"
version = "0.1.1"
edition = "2021"
authors = ["Joachim Fritscher <joachim.fritscher@gmail.com>"]
license = "MIT"
description = "Bindings to the C implementation of WFA2-lib"
repository = "https://github.com/4less/libwfa2"
readme = "readme.md"
keywords = ["bioinformatics", "alignment", "wfa"]
categories = ["science"]

[build-dependencies]
bindgen = "0.70.1"
clang-sys = "1.8.1"


[profile.release]
opt-level = 3               # Use best optimizations
overflow-checks = false     # Disable integer overflow checks.
rustflags = ["-C", "target-feature=+avx,+sse3,+avx2,+fma"]#
lto = "fat"

